version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: inventory-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: inventory-api
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://admin:admin123@mongo:27017/
      MONGO_DB: inventory_db

volumes:
  mongo_data: